#!/usr/bin/env python3

'''
2.0.1 version
-saves files as csv onto shared folder
'''

import sys
from datetime import datetime
from PyQt5.QtWidgets import (QMainWindow, QApplication, QWidget, QPushButton, 
	QComboBox, QLabel, QGridLayout, QGroupBox, QRadioButton, QVBoxLayout,
	QCheckBox, QLineEdit, QAction, QProgressBar, QCalendarWidget, QFileDialog,
        QColorDialog, QMessageBox, QFontDialog, QTextEdit)
from PyQt5.QtCore import pyqtSlot, Qt, QDate, QTime, QDateTime
from PyQt5.QtGui import QIcon, QColor

class App(QWidget):
	def __init__(self):
		super().__init__()
		self.title = 'End of Week Log'
		self.left = 10
		self.top = 30
		self.width = 1240
		self.height = 520
		
		#worm gear selections
		self.radio_wg_top_y = QRadioButton("Yes")
		self.radio_wg_top_n = QRadioButton("No")
		self.radio_wg_top_y.setChecked(True)
		self.radio_wg_side_y = QRadioButton("Yes")
		self.radio_wg_side_n = QRadioButton("No")
		self.radio_wg_side_y.setChecked(True)
		
		#saw selection
		self.saw_list = ['S1', 'S2', 'S4', 'S5', 'S7', 'S8', 'S9', 'S10', 'S11', 'S12',
			'S15', 'S17', 'S18', 'S19', 'S21', 'S25', 'S27', 'S28', 'S30', 'S250']
		self.saws = QComboBox()
		self.saws.addItems(self.saw_list)
		
		#bar entry
		self.bar = QLineEdit()
		
		#crew name entry
		self.crew_name = QLineEdit()
		
		#Misc entry
		self.misc = QTextEdit()
		self.misc.resize(75, 100)
		
		#date stamp
		self.date = QLineEdit()
		self.now = QDate.currentDate()
		self.date.setText(self.now.toString(Qt.ISODate))
		
		#start selection
		self.rad_start_y = QRadioButton("Yes")
		self.rad_start_n = QRadioButton("No")
		self.rad_start_na = QRadioButton("Not used")
		self.rad_start_n.setChecked(True)
		
		#filter selection
		self.rad_filt_swap = QRadioButton("Swapped")
		self.rad_filt_non = QRadioButton("No Filter")
		self.rad_filt_non.setChecked(True)
		
		#Clutch selections
		#operations
		self.chk_cltch_cln = QCheckBox("Cleaned")
		self.chk_cltch_grsd = QCheckBox("Greased")
		#damage selection
		self.rad_dmg_y = QRadioButton("Yes")
		self.rad_dmg_n = QRadioButton("No")
		self.rad_dmg_y.setChecked(True)
		#burn selection
		self.rad_brn_y = QRadioButton("Yes")
		self.rad_brn_n = QRadioButton("No")
		self.rad_brn_y.setChecked(True)
		
		#Bearing slections
		#grease check
		self.chk_bear_grsd = QCheckBox("Greased")
		#worn selection
		self.rad_bear_worn_y = QRadioButton("Yes")
		self.rad_bear_worn_n = QRadioButton("No")
		self.rad_bear_worn_y.setChecked(True)
		#beveled selection
		self.rad_bear_bev_y = QRadioButton("Yes")
		self.rad_bear_bev_n = QRadioButton("No")
		self.rad_bear_bev_y.setChecked(True)
		
		#sprocket selections
		#damage selection
		self.rad_spkt_dmg_y = QRadioButton("Yes")
		self.rad_spkt_dmg_n = QRadioButton("No")
		self.rad_spkt_dmg_y.setChecked(True)
		
		#chain catch intact selection
		self.rad_chnctch_y = QRadioButton("Yes")
		self.rad_chnctch_n = QRadioButton("No")
		self.rad_chnctch_n.setChecked(True)
		
		#bar checkoff list
		self.chk_bar_cln = QCheckBox("Cleaned")
		self.chk_bar_dbr = QCheckBox("Deburred")
		
		#spark plug selections
		self.rad_sprkp_disc_y = QRadioButton("Yes")
		self.rad_sprkp_disc_n = QRadioButton("No")
		self.rad_sprkp_wet_y = QRadioButton("Yes")
		self.rad_sprkp_wet_n = QRadioButton("No")
		self.rad_sprkp_cb_y = QRadioButton("Yes")
		self.rad_sprkp_cb_n = QRadioButton("No")
		self.rad_sprkp_disc_y.setChecked(True)
		self.rad_sprkp_wet_y.setChecked(True)
		self.rad_sprkp_cb_y.setChecked(True)
		
		#cap selections
		self.rad_oil_leak_y = QRadioButton("Yes")
		self.rad_oil_leak_n = QRadioButton("No")
		self.rad_gas_leak_y = QRadioButton("Yes")
		self.rad_gas_leak_n = QRadioButton("No")
		self.rad_gas_leak_y.setChecked(True)
		self.rad_oil_leak_y.setChecked(True)
		self.chk_oil_cln = QCheckBox("O-ring Cleaned")
		self.chk_gas_cln = QCheckBox("O-ring Cleaned")
		
		#Sliders checks
		self.chk_sldr_1 = QCheckBox("Slider 1")
		self.chk_sldr_2 = QCheckBox("Slider 2")
		
		#pull cor selections
		self.rad_pc_fray_y = QRadioButton("Yes")
		self.rad_pc_fray_n = QRadioButton("No")
		self.rad_pc_short_y = QRadioButton("Yes")
		self.rad_pc_short_n = QRadioButton("No")
		self.rad_pc_rtact_y = QRadioButton("Yes")
		self.rad_pc_rtact_n = QRadioButton("No")
		self.rad_pc_fray_y.setChecked(True)
		self.rad_pc_short_y.setChecked(True)
		self.rad_pc_rtact_n.setChecked(True)
		
		#create UI
		self.initUI()
		
	
	def initUI(self):
		self.setWindowTitle(self.title)
		self.setGeometry(self.left, self.top, self.width, self.height)
		
		grid = QGridLayout()
		grid.addWidget(self.createSawGroup(), 0, 0)
		grid.addWidget(self.createBarNumGroup(), 0, 1)
		grid.addWidget(self.createNameGroup(), 0, 2)
		grid.addWidget(self.createDateGroup(), 0, 3)
		grid.addWidget(self.createSAVE(), 0, 5)
		grid.addWidget(self.createStartGroup(), 1, 0)
		grid.addWidget(self.createFilterGroup(), 1, 1)
		grid.addWidget(self.createClutchGroup(), 1, 2)
		grid.addWidget(self.createBaringGroup(), 1, 3)
		grid.addWidget(self.createSprocketGroup(), 1, 4)
		grid.addWidget(self.createChainCatchGroup(), 1, 5)
		grid.addWidget(self.createWormGroup(), 2, 0)
		grid.addWidget(self.createBarGroup(), 2, 1)
		grid.addWidget(self.createSparkGroup(), 2, 2)
		grid.addWidget(self.createCapsGroup(), 2, 3)
		grid.addWidget(self.createSliderGroup(), 2, 4)
		grid.addWidget(self.createPullcordGroup(), 2, 5)
		grid.addWidget(self.createMiscGroup(), 1, 6, 5, 3)
		grid.setColumnStretch(6, 3)
		
		self.setLayout(grid)		
		
		saveFile = QAction("&Save File", self)
		saveFile.setShortcut("Ctrl+S")
		saveFile.setStatusTip('Save File')
		saveFile.triggered.connect(self.save_click)
		
		
		self.show()
	
	
        
	def createSAVE(self):
		save_button = QPushButton('&Save', self)
		save_button.setToolTip('Save all choices to a log')
		save_button.clicked.connect(self.save_click)
		
		return save_button
		
	@pyqtSlot()
	def save_click(self):
		options = QFileDialog.Options()
		options |= QFileDialog.DontUseNativeDialog
		auto_name = str(self.saws.currentText()) + "-" + str(self.date.text())
		name, _ = QFileDialog.getSaveFileName(self,"QFileDialog.getSaveFileName()",auto_name,"All Files (*);;Text Files (*.txt)", options=options)
		
		
		
		try:
			file = open(name, 'w+')
			text = self.output_text()
			file.write(str(text).replace("[", ''))
			file.close()
		except:
			pass
			
	def createMiscGroup(self):
		groupBox = QGroupBox("Misc.")
		vbox = QVBoxLayout()
		vbox.addWidget(self.misc)
		vbox.addStretch(1)
		groupBox.setLayout(vbox)
		return groupBox
		
	def createWormGroup(self):
		groupBox = QGroupBox("Worm Gear")
		
		#inner top wear group		
		topGroup = QGroupBox("Top Wear")
		top_vbox = QVBoxLayout()
		top_vbox.addWidget(self.radio_wg_top_y)
		top_vbox.addWidget(self.radio_wg_top_n)
		top_vbox.addStretch(1)
		topGroup.setLayout(top_vbox)
		
		#inner side wear group
		sideGroup = QGroupBox("Side Wear")
		side_vbox = QVBoxLayout()
		side_vbox.addWidget(self.radio_wg_side_y)
		side_vbox.addWidget(self.radio_wg_side_n)
		side_vbox.addStretch(1)
		sideGroup.setLayout(side_vbox)

		#Worm gear group
		vbox = QVBoxLayout()
		vbox.addWidget(topGroup)
		vbox.addWidget(sideGroup)
		vbox.addStretch(1)
		groupBox.setLayout(vbox)
		
		return groupBox
		
	def output_text(self):
		
		master_output = []
					
		#saw selection index:0
		saw = str(self.saws.currentText())
		master_output.append(saw)
		
		#date stamp datetime.strptime(*arg, '%Y,%m,%d') index:1
		today = datetime.strptime(self.date.text(), '%Y-%m-%d')
		master_output.append(today)
				
		#bar entry index:2
		bar = self.bar.text()
		master_output.append(bar)
		
		#crew name entry index:3
		crew = self.crew_name.text()
		master_output.append(crew)
		
		#start selection index:4
		if self.rad_start_y.isChecked():
			starts = True
		elif self.rad_start_n.isChecked():
			starts = False
		else:
			starts = False
		master_output.append(starts)
		
		#filter selection index:5
		if self.rad_filt_swap.isChecked():
			air_filter = True
		else:
			air_filter = False
		master_output.append(air_filter)
		
		#worm gear selections output index:6-7
		if self.radio_wg_top_y.isChecked():
			worm_gear = True
		else:
			worm_gear = False
		master_output.append(worm_gear)
		if self.radio_wg_side_y.isChecked():
			worm_gear = True
		else:
			worm_gear = False
		master_output.append(worm_gear)
	
		#Clutch output
		#operations index:8-11
		clutch_out = bool()
		if self.chk_cltch_cln.isChecked() == False:
			clutch_out = False
		else:
			clutch_out = True
		master_output.append(clutch_out)
		if self.chk_cltch_grsd.isChecked() == False:
			clutch_out = False
		else:
			clutch_out = True
		master_output.append(clutch_out)
		#damage selection
		if self.rad_dmg_y.isChecked():
			clutch_out = False
		else:
			clutch_out = True
		master_output.append(clutch_out)
		#burn selection
		if self.rad_brn_y.isChecked():
			clutch_out = False
		else:
			clutch_out = True
		master_output.append(clutch_out)
		
		#Bearing slections index:12-14
		#grease check
		bearing_out = bool()
		if self.chk_bear_grsd.isChecked() == False:
			bearing_out = False
		else:
			bearing_out = True
		master_output.append(bearing_out)
		#worn selection
		if self.rad_bear_worn_y.isChecked():
			bearing_out = True
		else:
			bearing_out = False
		master_output.append(bearing_out)
		#beveled selection
		if self.rad_bear_bev_y.isChecked():
			bearing_out = False
		else:
			bearing_out = True
		master_output.append(bearing_out)
		
		#sprocket selections index:15
		#damage selection
		sprocket_out = bool()
		if self.rad_spkt_dmg_y.isChecked():
			sprocket_out = True
		else:
			 sprocket_out = False
		master_output.append(sprocket_out)
				
		#chain catch intact selection index:16
		chain_catch_out = bool()
		if self.rad_chnctch_n.isChecked():
			chain_catch_out = False
		else:
			chain_catch_out = True
		master_output.append(chain_catch_out)
		
		#bar checkoff list index:17-18
		bar_out = bool()
		if self.chk_bar_cln.isChecked() == False:
			bar_out = False
		else:
			bar_out = True
		master_output.append(bar_out)
		if self.chk_bar_dbr.isChecked() == False:
			bar_out = False
		else:
			bar_out = True
		master_output.append(bar_out)
		
		#spark plug selections index:19-21
		spark_plug_out = bool()
		if self.rad_sprkp_disc_y.isChecked():
			spark_plug_out = False
		else:
			spark_plug_out = True
		master_output.append(spark_plug_out)
		if self.rad_sprkp_wet_y.isChecked():
			spark_plug_out = False
		else:
			spark_plug_out = True
		master_output.append(spark_plug_out)
		if self.rad_sprkp_cb_y.isChecked():
			spark_plug_out = False
		else:
			spark_plug_out = True
		master_output.append(spark_plug_out)
		
		
		#cap selections index:22-25
		caps_out = bool()
		if self.rad_oil_leak_y.isChecked():
			caps_out = False
		else:
			caps_out = True
		master_output.append(caps_out)
		if self.rad_gas_leak_y.isChecked():
			caps_out = False
		else:
			caps_out = True
		master_output.append(caps_out)
		if self.chk_oil_cln.isChecked() == False:
			caps_out = False
		else:
			caps_out = True
		master_output.append(caps_out)
		if self.chk_gas_cln.isChecked() == False:
			caps_out = False
		else:
			caps_out = True
		master_output.append(caps_out)
		
		#Sliders checks index:26-27
		sliders_out = bool()
		if self.chk_sldr_1.isChecked() == False:
			sliders_out = False
		else:
			sliders_out = True
		master_output.append(sliders_out)
		if self.chk_sldr_2.isChecked() == False:
			sliders_out = False
		else:
			sliders_out = True
		master_output.append(sliders_out)
		
		#pull cord selections index:28-30
		pull_cord_out = bool()
		if self.rad_pc_fray_y.isChecked():
			pull_cord_out = False
		else:
			pull_cord_out = True
		master_output.append(pull_cord_out)
		if self.rad_pc_short_y.isChecked():
			pull_cord_out = False
		else:
			pull_cord_out = True
		master_output.append(pull_cord_out)
		if self.rad_pc_rtact_n.isChecked():
			pull_cord_out = False
		else:
			pull_cord_out = True
		master_output.append(pull_cord_out)
		
		#misc comments
		misc_out = str(self.misc.toPlainText())
		master_output.append(misc_out)
		
		master_string = str()
		for ind in master_output:
			master_string += str(ind) + ','
		master_string[:-1]
		
		return master_string
		
	def createSawGroup(self):
		groupBox = QGroupBox("Saw")
		box = QVBoxLayout()
		
		box.addWidget(self.saws)
		box.addStretch(1)

		groupBox.setLayout(box)
		
		return groupBox
		
	def createBarNumGroup(self):
		groupBox = QGroupBox("Bar #")
		
		box = QVBoxLayout()
		box.addWidget(self.bar)
		box.addStretch(1)
		groupBox.setLayout(box)
		
		return groupBox
		
	def createNameGroup(self):
		groupBox = QGroupBox("Name")
		
		box = QVBoxLayout()
		box.addWidget(self.crew_name)
		box.addStretch(1)
		groupBox.setLayout(box)
		
		return groupBox
		
	def createDateGroup(self):
		groupBox = QGroupBox("Date")
		
		box = QVBoxLayout()
		box.addWidget(self.date)
		box.addStretch(1)
		
		groupBox.setLayout(box)
		
		return groupBox
		
	def createStartGroup(self):
		groupBox = QGroupBox("Starts")

		vbox = QVBoxLayout()
		vbox.addWidget(self.rad_start_y)
		vbox.addWidget(self.rad_start_n)
		vbox.addWidget(self.rad_start_na)
		vbox.addStretch(1)
		groupBox.setLayout(vbox)

		return groupBox
		
	def createFilterGroup(self):
		groupBox = QGroupBox("Air Filter")

		vbox = QVBoxLayout()
		vbox.addWidget(self.rad_filt_swap)
		vbox.addWidget(self.rad_filt_non)
		vbox.addStretch(1)
		groupBox.setLayout(vbox)

		return groupBox
		
	def createClutchGroup(self):
		groupBox = QGroupBox("Clutch Drum")
		
		damGroup = QGroupBox("Damage")
		dam_vbox = QVBoxLayout()
		dam_vbox.addWidget(self.rad_dmg_y)
		dam_vbox.addWidget(self.rad_dmg_n)
		dam_vbox.addStretch(1)
		damGroup.setLayout(dam_vbox)
		
		burnGroup = QGroupBox("Burns")
		burn_vbox = QVBoxLayout()
		burn_vbox.addWidget(self.rad_brn_y)
		burn_vbox.addWidget(self.rad_brn_n)
		burn_vbox.addStretch(1)
		burnGroup.setLayout(burn_vbox)

		#Clutch drum group
		vbox = QVBoxLayout()
		vbox.addWidget(self.chk_cltch_cln)
		vbox.addWidget(self.chk_cltch_grsd)
		vbox.addWidget(damGroup)
		vbox.addWidget(burnGroup)
		vbox.addStretch(1)
		groupBox.setLayout(vbox)

		return groupBox
		
	def createBaringGroup(self):
		groupBox = QGroupBox("Clutch Bearing")

		wornGroup = QGroupBox("Worn")
		worn_vbox = QVBoxLayout()
		worn_vbox.addWidget(self.rad_bear_worn_y)
		worn_vbox.addWidget(self.rad_bear_worn_n)
		worn_vbox.addStretch(1)
		wornGroup.setLayout(worn_vbox)
		
		bevelGroup = QGroupBox("Beveled")
		bevel_vbox = QVBoxLayout()
		bevel_vbox.addWidget(self.rad_bear_bev_y)
		bevel_vbox.addWidget(self.rad_bear_bev_n)
		bevel_vbox.addStretch(1)
		bevelGroup.setLayout(bevel_vbox)

		#Clutch baring group
		vbox = QVBoxLayout()
		vbox.addWidget(self.chk_bear_grsd)
		vbox.addWidget(wornGroup)
		vbox.addWidget(bevelGroup)
		vbox.addStretch(1)
		groupBox.setLayout(vbox)

		return groupBox
		
	def createSprocketGroup(self):
		groupBox = QGroupBox("Sprocket")
		
		damGroup = QGroupBox("Worn")
		dam_vbox = QVBoxLayout()
		dam_vbox.addWidget(self.rad_spkt_dmg_y)
		dam_vbox.addWidget(self.rad_spkt_dmg_n)
		dam_vbox.addStretch(1)
		damGroup.setLayout(dam_vbox)

		#Sprocket group
		vbox = QVBoxLayout()
		vbox.addWidget(damGroup)
		vbox.addStretch(1)
		groupBox.setLayout(vbox)

		return groupBox
		
	def createChainCatchGroup(self):
		groupBox = QGroupBox("Chain Catch")
		
		intGroup = QGroupBox("Intact")
		int_vbox = QVBoxLayout()
		int_vbox.addWidget(self.rad_chnctch_n)
		int_vbox.addWidget(self.rad_chnctch_y)
		int_vbox.addStretch(1)
		intGroup.setLayout(int_vbox)

		#Chain-catch group
		vbox = QVBoxLayout()
		vbox.addWidget(intGroup)
		vbox.addStretch(1)
		groupBox.setLayout(vbox)

		return groupBox
		
	def createBarGroup(self):
		groupBox = QGroupBox("Bar")
		
		vbox = QVBoxLayout()
		vbox.addWidget(self.chk_bar_cln)
		vbox.addWidget(self.chk_bar_dbr)
		vbox.addStretch(1)
		groupBox.setLayout(vbox)
		
		return groupBox
		
	def createSparkGroup(self):
		groupBox = QGroupBox("Sparkplug")
			
		#inner discolor group
		dcgroup = QGroupBox("Discolored")
		dc_vbox = QVBoxLayout()
		dc_vbox.addWidget(self.rad_sprkp_disc_y)
		dc_vbox.addWidget(self.rad_sprkp_disc_n)
		dc_vbox.addStretch(1)
		dcgroup.setLayout(dc_vbox)
		
		
		#inner wet group
		wetgroup = QGroupBox("Wet")
		wet_vbox = QVBoxLayout()
		wet_vbox.addWidget(self.rad_sprkp_wet_y)
		wet_vbox.addWidget(self.rad_sprkp_wet_n)
		wet_vbox.addStretch(1)
		wetgroup.setLayout(wet_vbox)
		
		#inner carbon build-up group
		carbongroup = QGroupBox("Carbon Build-up")
		car_vbox = QVBoxLayout()
		car_vbox.addWidget(self.rad_sprkp_cb_y)
		car_vbox.addWidget(self.rad_sprkp_cb_n)
		car_vbox.addStretch(1)
		carbongroup.setLayout(car_vbox)
		
		#sparkplug group
		vbox = QVBoxLayout()
		vbox.addWidget(dcgroup)
		vbox.addWidget(wetgroup)
		vbox.addWidget(carbongroup)
		vbox.addStretch(1)
		groupBox.setLayout(vbox)
		
		return groupBox
		
	def createCapsGroup(self):
		groupBox = QGroupBox("Caps")
		
		#inner oil group
		oil_group = QGroupBox("Oil")
		oil_vbox = QVBoxLayout()
		oil_vbox.addWidget(self.chk_oil_cln)
		#inner inner leak group
		oil_leak_group = QGroupBox("Leaks")
		leak_vbox = QVBoxLayout()
		leak_vbox.addWidget(self.rad_oil_leak_y)
		leak_vbox.addWidget(self.rad_oil_leak_n)
		leak_vbox.addStretch(1)
		oil_leak_group.setLayout(leak_vbox)
		#end inner inner....
		oil_vbox.addWidget(oil_leak_group)
		oil_vbox.addStretch(1)
		oil_group.setLayout(oil_vbox)
		
		#inner gas group
		gas_group = QGroupBox("Gas")
		gas_vbox = QVBoxLayout()
		gas_vbox.addWidget(self.chk_gas_cln)
		#inner inner leak group
		gas_leak_group = QGroupBox("Leaks")
		gleak_vbox = QVBoxLayout()
		gleak_vbox.addWidget(self.rad_gas_leak_y)
		gleak_vbox.addWidget(self.rad_gas_leak_n)
		gleak_vbox.addStretch(1)
		gas_leak_group.setLayout(gleak_vbox)
		#end inner inner....
		gas_vbox.addWidget(gas_leak_group)
		gas_vbox.addStretch(1)
		gas_group.setLayout(gas_vbox)
		
		#caps group
		vbox = QVBoxLayout()
		vbox.addWidget(oil_group)
		vbox.addWidget(gas_group)
		vbox.addStretch(1)
		groupBox.setLayout(vbox)
		
		return groupBox
		
	def createSliderGroup(self):
		groupBox = QGroupBox("Sliders")
		sliderGroup = QGroupBox("In Place")
		
		slider_vbox = QVBoxLayout()
		slider_vbox.addWidget(self.chk_sldr_1)
		slider_vbox.addWidget(self.chk_sldr_2)
		slider_vbox.addStretch(1)
		sliderGroup.setLayout(slider_vbox)
		
		vbox = QVBoxLayout()
		vbox.addWidget(sliderGroup)
		vbox.addStretch(1)
		groupBox.setLayout(vbox)
		
		return groupBox
		
	def createPullcordGroup(self):
		groupBox = QGroupBox("Pull Cord")
		fray_group = QGroupBox("Frayed")
		short_group = QGroupBox("Short Pull")
		ret_group = QGroupBox("Fully Retracts")
		
		#inner fray group
		fray_vbox = QVBoxLayout()
		fray_vbox.addWidget(self.rad_pc_fray_y)
		fray_vbox.addWidget(self.rad_pc_fray_n)
		fray_vbox.addStretch(1)
		fray_group.setLayout(fray_vbox)
		
		#inner short pull group
		short_vbox = QVBoxLayout()
		short_vbox.addWidget(self.rad_pc_short_y)
		short_vbox.addWidget(self.rad_pc_short_n)
		short_vbox.addStretch(1)
		short_group.setLayout(short_vbox)
		
		#inner full retract group
		ret_vbox = QVBoxLayout()
		ret_vbox.addWidget(self.rad_pc_rtact_n)
		ret_vbox.addWidget(self.rad_pc_rtact_y)
		ret_vbox.addStretch(1)
		ret_group.setLayout(ret_vbox)
		
		#pull cord group
		vbox = QVBoxLayout()
		vbox.addWidget(fray_group)
		vbox.addWidget(short_group)
		vbox.addWidget(ret_group)
		vbox.addStretch(1)
		groupBox.setLayout(vbox)
		
		return groupBox

		
		
#execute application
if __name__ == '__main__':
	app = QApplication(sys.argv)
	ex = App()
sys.exit(app.exec_())
